// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: flight-service/proto/flight.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFlightsWithAirportsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *GetFlightsWithAirportsRequest) Reset() {
	*x = GetFlightsWithAirportsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_service_proto_flight_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlightsWithAirportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlightsWithAirportsRequest) ProtoMessage() {}

func (x *GetFlightsWithAirportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flight_service_proto_flight_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlightsWithAirportsRequest.ProtoReflect.Descriptor instead.
func (*GetFlightsWithAirportsRequest) Descriptor() ([]byte, []int) {
	return file_flight_service_proto_flight_proto_rawDescGZIP(), []int{0}
}

func (x *GetFlightsWithAirportsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetFlightsWithAirportsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetFlightsWithAirportsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page          int32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	TotalElements int32                 `protobuf:"varint,3,opt,name=totalElements,proto3" json:"totalElements,omitempty"`
	Items         []*FlightWithAirports `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetFlightsWithAirportsResponse) Reset() {
	*x = GetFlightsWithAirportsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_service_proto_flight_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlightsWithAirportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlightsWithAirportsResponse) ProtoMessage() {}

func (x *GetFlightsWithAirportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flight_service_proto_flight_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlightsWithAirportsResponse.ProtoReflect.Descriptor instead.
func (*GetFlightsWithAirportsResponse) Descriptor() ([]byte, []int) {
	return file_flight_service_proto_flight_proto_rawDescGZIP(), []int{1}
}

func (x *GetFlightsWithAirportsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetFlightsWithAirportsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetFlightsWithAirportsResponse) GetTotalElements() int32 {
	if x != nil {
		return x.TotalElements
	}
	return 0
}

func (x *GetFlightsWithAirportsResponse) GetItems() []*FlightWithAirports {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetFlightWithAirportsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlightNumber string `protobuf:"bytes,1,opt,name=flightNumber,proto3" json:"flightNumber,omitempty"`
}

func (x *GetFlightWithAirportsRequest) Reset() {
	*x = GetFlightWithAirportsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_service_proto_flight_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlightWithAirportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlightWithAirportsRequest) ProtoMessage() {}

func (x *GetFlightWithAirportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flight_service_proto_flight_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlightWithAirportsRequest.ProtoReflect.Descriptor instead.
func (*GetFlightWithAirportsRequest) Descriptor() ([]byte, []int) {
	return file_flight_service_proto_flight_proto_rawDescGZIP(), []int{2}
}

func (x *GetFlightWithAirportsRequest) GetFlightNumber() string {
	if x != nil {
		return x.FlightNumber
	}
	return ""
}

type GetFlightWithAirportsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flight *FlightWithAirports `protobuf:"bytes,1,opt,name=flight,proto3" json:"flight,omitempty"`
}

func (x *GetFlightWithAirportsResponse) Reset() {
	*x = GetFlightWithAirportsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_service_proto_flight_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlightWithAirportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlightWithAirportsResponse) ProtoMessage() {}

func (x *GetFlightWithAirportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flight_service_proto_flight_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlightWithAirportsResponse.ProtoReflect.Descriptor instead.
func (*GetFlightWithAirportsResponse) Descriptor() ([]byte, []int) {
	return file_flight_service_proto_flight_proto_rawDescGZIP(), []int{3}
}

func (x *GetFlightWithAirportsResponse) GetFlight() *FlightWithAirports {
	if x != nil {
		return x.Flight
	}
	return nil
}

type FlightWithAirports struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID           int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	FlightNumber string                 `protobuf:"bytes,2,opt,name=flightNumber,proto3" json:"flightNumber,omitempty"`
	FromAirport  string                 `protobuf:"bytes,3,opt,name=fromAirport,proto3" json:"fromAirport,omitempty"`
	ToAirport    string                 `protobuf:"bytes,4,opt,name=toAirport,proto3" json:"toAirport,omitempty"`
	Date         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Price        int32                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *FlightWithAirports) Reset() {
	*x = FlightWithAirports{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_service_proto_flight_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlightWithAirports) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightWithAirports) ProtoMessage() {}

func (x *FlightWithAirports) ProtoReflect() protoreflect.Message {
	mi := &file_flight_service_proto_flight_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightWithAirports.ProtoReflect.Descriptor instead.
func (*FlightWithAirports) Descriptor() ([]byte, []int) {
	return file_flight_service_proto_flight_proto_rawDescGZIP(), []int{4}
}

func (x *FlightWithAirports) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *FlightWithAirports) GetFlightNumber() string {
	if x != nil {
		return x.FlightNumber
	}
	return ""
}

func (x *FlightWithAirports) GetFromAirport() string {
	if x != nil {
		return x.FromAirport
	}
	return ""
}

func (x *FlightWithAirports) GetToAirport() string {
	if x != nil {
		return x.ToAirport
	}
	return ""
}

func (x *FlightWithAirports) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *FlightWithAirports) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateFlightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flight *Flight `protobuf:"bytes,1,opt,name=flight,proto3" json:"flight,omitempty"`
}

func (x *CreateFlightRequest) Reset() {
	*x = CreateFlightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_service_proto_flight_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlightRequest) ProtoMessage() {}

func (x *CreateFlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flight_service_proto_flight_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlightRequest.ProtoReflect.Descriptor instead.
func (*CreateFlightRequest) Descriptor() ([]byte, []int) {
	return file_flight_service_proto_flight_proto_rawDescGZIP(), []int{5}
}

func (x *CreateFlightRequest) GetFlight() *Flight {
	if x != nil {
		return x.Flight
	}
	return nil
}

type CreateFlightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateFlightResponse) Reset() {
	*x = CreateFlightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_service_proto_flight_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFlightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlightResponse) ProtoMessage() {}

func (x *CreateFlightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flight_service_proto_flight_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlightResponse.ProtoReflect.Descriptor instead.
func (*CreateFlightResponse) Descriptor() ([]byte, []int) {
	return file_flight_service_proto_flight_proto_rawDescGZIP(), []int{6}
}

type Flight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	FlightNumber  string                 `protobuf:"bytes,2,opt,name=flightNumber,proto3" json:"flightNumber,omitempty"`
	FromAirportID int32                  `protobuf:"varint,3,opt,name=fromAirportID,proto3" json:"fromAirportID,omitempty"`
	ToAirportID   int32                  `protobuf:"varint,4,opt,name=toAirportID,proto3" json:"toAirportID,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Price         int32                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *Flight) Reset() {
	*x = Flight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_service_proto_flight_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Flight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flight) ProtoMessage() {}

func (x *Flight) ProtoReflect() protoreflect.Message {
	mi := &file_flight_service_proto_flight_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flight.ProtoReflect.Descriptor instead.
func (*Flight) Descriptor() ([]byte, []int) {
	return file_flight_service_proto_flight_proto_rawDescGZIP(), []int{7}
}

func (x *Flight) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Flight) GetFlightNumber() string {
	if x != nil {
		return x.FlightNumber
	}
	return ""
}

func (x *Flight) GetFromAirportID() int32 {
	if x != nil {
		return x.FromAirportID
	}
	return 0
}

func (x *Flight) GetToAirportID() int32 {
	if x != nil {
		return x.ToAirportID
	}
	return 0
}

func (x *Flight) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Flight) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateAirportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Airport *Airport `protobuf:"bytes,1,opt,name=airport,proto3" json:"airport,omitempty"`
}

func (x *CreateAirportRequest) Reset() {
	*x = CreateAirportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_service_proto_flight_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAirportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAirportRequest) ProtoMessage() {}

func (x *CreateAirportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flight_service_proto_flight_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAirportRequest.ProtoReflect.Descriptor instead.
func (*CreateAirportRequest) Descriptor() ([]byte, []int) {
	return file_flight_service_proto_flight_proto_rawDescGZIP(), []int{8}
}

func (x *CreateAirportRequest) GetAirport() *Airport {
	if x != nil {
		return x.Airport
	}
	return nil
}

type CreateAirportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAirportResponse) Reset() {
	*x = CreateAirportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_service_proto_flight_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAirportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAirportResponse) ProtoMessage() {}

func (x *CreateAirportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flight_service_proto_flight_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAirportResponse.ProtoReflect.Descriptor instead.
func (*CreateAirportResponse) Descriptor() ([]byte, []int) {
	return file_flight_service_proto_flight_proto_rawDescGZIP(), []int{9}
}

type Airport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	City    string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Country string `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
}

func (x *Airport) Reset() {
	*x = Airport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_service_proto_flight_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Airport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Airport) ProtoMessage() {}

func (x *Airport) ProtoReflect() protoreflect.Message {
	mi := &file_flight_service_proto_flight_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Airport.ProtoReflect.Descriptor instead.
func (*Airport) Descriptor() ([]byte, []int) {
	return file_flight_service_proto_flight_proto_rawDescGZIP(), []int{10}
}

func (x *Airport) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Airport) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Airport) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Airport) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

var File_flight_service_proto_flight_proto protoreflect.FileDescriptor

var file_flight_service_proto_flight_proto_rawDesc = []byte{
	0x0a, 0x21, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x1d,
	0x47, 0x65, 0x74, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x57, 0x69, 0x74, 0x68, 0x41, 0x69,
	0x72, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0xa8, 0x01, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x57, 0x69, 0x74, 0x68, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x30,
	0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x57, 0x69, 0x74,
	0x68, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x22, 0x42, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x57, 0x69, 0x74,
	0x68, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x22, 0x0a, 0x0c, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x22, 0x53, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x57, 0x69, 0x74, 0x68, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x46,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x57, 0x69, 0x74, 0x68, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74,
	0x73, 0x52, 0x06, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x22, 0xce, 0x01, 0x0a, 0x12, 0x46, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x57, 0x69, 0x74, 0x68, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x22, 0x0a, 0x0c, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x41, 0x69, 0x72, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x41,
	0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x41, 0x69, 0x72, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x41, 0x69, 0x72,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x3d, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x26, 0x0a, 0x06, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x52, 0x06, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0xca, 0x01, 0x0a, 0x06, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c,
	0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x24, 0x0a, 0x0d, 0x66, 0x72, 0x6f, 0x6d, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x66, 0x72, 0x6f, 0x6d, 0x41, 0x69, 0x72,
	0x70, 0x6f, 0x72, 0x74, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x41, 0x69, 0x72, 0x70,
	0x6f, 0x72, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x6f, 0x41,
	0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x44, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x41,
	0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x07, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x2e, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x07, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72,
	0x74, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x69, 0x72, 0x70, 0x6f,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5b, 0x0a, 0x07, 0x41, 0x69,
	0x72, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x32, 0xf7, 0x02, 0x0a, 0x0d, 0x46, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x67, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x57, 0x69, 0x74, 0x68, 0x41, 0x69, 0x72, 0x70, 0x6f,
	0x72, 0x74, 0x73, 0x12, 0x25, 0x2e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x47, 0x65, 0x74,
	0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x57, 0x69, 0x74, 0x68, 0x41, 0x69, 0x72, 0x70, 0x6f,
	0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x66, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x57, 0x69,
	0x74, 0x68, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x64, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x57,
	0x69, 0x74, 0x68, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x24, 0x2e, 0x66, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x57, 0x69,
	0x74, 0x68, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x25, 0x2e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x57, 0x69, 0x74, 0x68, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1b, 0x2e, 0x66, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x69, 0x72,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x1c, 0x2e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x64, 0x65, 0x61, 0x64, 0x73, 0x68, 0x76, 0x74, 0x2f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_flight_service_proto_flight_proto_rawDescOnce sync.Once
	file_flight_service_proto_flight_proto_rawDescData = file_flight_service_proto_flight_proto_rawDesc
)

func file_flight_service_proto_flight_proto_rawDescGZIP() []byte {
	file_flight_service_proto_flight_proto_rawDescOnce.Do(func() {
		file_flight_service_proto_flight_proto_rawDescData = protoimpl.X.CompressGZIP(file_flight_service_proto_flight_proto_rawDescData)
	})
	return file_flight_service_proto_flight_proto_rawDescData
}

var file_flight_service_proto_flight_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_flight_service_proto_flight_proto_goTypes = []any{
	(*GetFlightsWithAirportsRequest)(nil),  // 0: flight.GetFlightsWithAirportsRequest
	(*GetFlightsWithAirportsResponse)(nil), // 1: flight.GetFlightsWithAirportsResponse
	(*GetFlightWithAirportsRequest)(nil),   // 2: flight.GetFlightWithAirportsRequest
	(*GetFlightWithAirportsResponse)(nil),  // 3: flight.GetFlightWithAirportsResponse
	(*FlightWithAirports)(nil),             // 4: flight.FlightWithAirports
	(*CreateFlightRequest)(nil),            // 5: flight.CreateFlightRequest
	(*CreateFlightResponse)(nil),           // 6: flight.CreateFlightResponse
	(*Flight)(nil),                         // 7: flight.Flight
	(*CreateAirportRequest)(nil),           // 8: flight.CreateAirportRequest
	(*CreateAirportResponse)(nil),          // 9: flight.CreateAirportResponse
	(*Airport)(nil),                        // 10: flight.Airport
	(*timestamppb.Timestamp)(nil),          // 11: google.protobuf.Timestamp
}
var file_flight_service_proto_flight_proto_depIdxs = []int32{
	4,  // 0: flight.GetFlightsWithAirportsResponse.items:type_name -> flight.FlightWithAirports
	4,  // 1: flight.GetFlightWithAirportsResponse.flight:type_name -> flight.FlightWithAirports
	11, // 2: flight.FlightWithAirports.date:type_name -> google.protobuf.Timestamp
	7,  // 3: flight.CreateFlightRequest.flight:type_name -> flight.Flight
	11, // 4: flight.Flight.date:type_name -> google.protobuf.Timestamp
	10, // 5: flight.CreateAirportRequest.airport:type_name -> flight.Airport
	0,  // 6: flight.FlightService.GetFlightsWithAirports:input_type -> flight.GetFlightsWithAirportsRequest
	2,  // 7: flight.FlightService.GetFlightWithAirports:input_type -> flight.GetFlightWithAirportsRequest
	5,  // 8: flight.FlightService.CreateFlight:input_type -> flight.CreateFlightRequest
	8,  // 9: flight.FlightService.CreateAirport:input_type -> flight.CreateAirportRequest
	1,  // 10: flight.FlightService.GetFlightsWithAirports:output_type -> flight.GetFlightsWithAirportsResponse
	3,  // 11: flight.FlightService.GetFlightWithAirports:output_type -> flight.GetFlightWithAirportsResponse
	6,  // 12: flight.FlightService.CreateFlight:output_type -> flight.CreateFlightResponse
	9,  // 13: flight.FlightService.CreateAirport:output_type -> flight.CreateAirportResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_flight_service_proto_flight_proto_init() }
func file_flight_service_proto_flight_proto_init() {
	if File_flight_service_proto_flight_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_flight_service_proto_flight_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetFlightsWithAirportsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_service_proto_flight_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetFlightsWithAirportsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_service_proto_flight_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetFlightWithAirportsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_service_proto_flight_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetFlightWithAirportsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_service_proto_flight_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*FlightWithAirports); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_service_proto_flight_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CreateFlightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_service_proto_flight_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*CreateFlightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_service_proto_flight_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Flight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_service_proto_flight_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CreateAirportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_service_proto_flight_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*CreateAirportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_service_proto_flight_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*Airport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_flight_service_proto_flight_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flight_service_proto_flight_proto_goTypes,
		DependencyIndexes: file_flight_service_proto_flight_proto_depIdxs,
		MessageInfos:      file_flight_service_proto_flight_proto_msgTypes,
	}.Build()
	File_flight_service_proto_flight_proto = out.File
	file_flight_service_proto_flight_proto_rawDesc = nil
	file_flight_service_proto_flight_proto_goTypes = nil
	file_flight_service_proto_flight_proto_depIdxs = nil
}
